# Generated by Django 3.2.3 on 2021-05-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyrequirements',
            name='title',
        ),
    ]
