# Generated by Django 3.2.3 on 2021-05-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_vacancyrequirements_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
