# Generated by Django 3.2.3 on 2021-05-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20210515_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(blank=True, db_column='skill', null=True, verbose_name='skill')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.courses')),
            ],
        ),
    ]
