# Generated by Django 3.2.3 on 2021-05-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_courseskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='address',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='salary',
            field=models.CharField(db_column='salary', default='По договору', max_length=64, verbose_name='зп'),
        ),
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='Свободный график', max_length=64)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.vacancies')),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.vacancies')),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=240)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.vacancies')),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=240)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.vacancies')),
            ],
        ),
    ]
